#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.4.30f1_ad8d9fbddd5b"
#define UNITY_VERSION_FULL_NICE "2018.4.30f1 (ad8d9fbddd5b)"
#define UNITY_VERSION_BLD 11373983
#define UNITY_VERSION_DATE 1606437994
#define UNITY_VERSION_WIN "2018.4.30.11373983"
#define UNITY_VERSION_BRANCH "2018.4/china_unity/release"
